//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace client.Resources.String {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("client.Resources.String.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồng ý.
        /// </summary>
        public static string AlertAgree {
            get {
                return ResourceManager.GetString("AlertAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Để sau.
        /// </summary>
        public static string AlertLater {
            get {
                return ResourceManager.GetString("AlertLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu đăng nhập.
        /// </summary>
        public static string AlertLoginRequiredTitle {
            get {
                return ResourceManager.GetString("AlertLoginRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn cần đăng nhập để có thể lưu địa điểm yêu thích. Đăng nhập ngay?.
        /// </summary>
        public static string AlertLoginToFavorite {
            get {
                return ResourceManager.GetString("AlertLoginToFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn cần đăng nhập để viết đánh giá và bình luận. Đăng nhập ngay?.
        /// </summary>
        public static string AlertLoginToReview {
            get {
                return ResourceManager.GetString("AlertLoginToReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        public static string AlertNotice {
            get {
                return ResourceManager.GetString("AlertNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string AlertOK {
            get {
                return ResourceManager.GetString("AlertOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đánh giá của bạn đã được ghi nhận thành công..
        /// </summary>
        public static string AlertReviewSuccess {
            get {
                return ResourceManager.GetString("AlertReviewSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn số sao đánh giá (từ 1 đến 5)..
        /// </summary>
        public static string AlertSelectStar {
            get {
                return ResourceManager.GetString("AlertSelectStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảm ơn!.
        /// </summary>
        public static string AlertThankYou {
            get {
                return ResourceManager.GetString("AlertThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả địa điểm.
        /// </summary>
        public static string AllLocations {
            get {
                return ResourceManager.GetString("AllLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❤️ Thêm vào yêu thích.
        /// </summary>
        public static string DetailAddFavorite {
            get {
                return ResourceManager.GetString("DetailAddFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huỷ bỏ.
        /// </summary>
        public static string DetailCancel {
            get {
                return ResourceManager.GetString("DetailCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chạm để khám phá thêm về địa điểm này..
        /// </summary>
        public static string DetailDefaultDesc {
            get {
                return ResourceManager.GetString("DetailDefaultDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khu ẩm thực Vĩnh Khánh.
        /// </summary>
        public static string DetailLocationDemo {
            get {
                return ResourceManager.GetString("DetailLocationDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có thông tin thực đơn..
        /// </summary>
        public static string DetailMenuEmpty {
            get {
                return ResourceManager.GetString("DetailMenuEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thực đơn nổi bật.
        /// </summary>
        public static string DetailMenuTitle {
            get {
                return ResourceManager.GetString("DetailMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang cập nhật thực đơn....
        /// </summary>
        public static string DetailMenuUpdating {
            get {
                return ResourceManager.GetString("DetailMenuUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💔 Bỏ yêu thích.
        /// </summary>
        public static string DetailRemoveFavorite {
            get {
                return ResourceManager.GetString("DetailRemoveFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chia sẻ trải nghiệm của bạn tại đây....
        /// </summary>
        public static string DetailReviewPlaceholder {
            get {
                return ResourceManager.GetString("DetailReviewPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đánh giá &amp; Bình luận.
        /// </summary>
        public static string DetailReviewTitle {
            get {
                return ResourceManager.GetString("DetailReviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi đánh giá.
        /// </summary>
        public static string DetailSubmitReview {
            get {
                return ResourceManager.GetString("DetailSubmitReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viết đánh giá của bạn.
        /// </summary>
        public static string DetailWriteReview {
            get {
                return ResourceManager.GetString("DetailWriteReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn (Demo).
        /// </summary>
        public static string DetailYouDemo {
            get {
                return ResourceManager.GetString("DetailYouDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đánh giá của bạn.
        /// </summary>
        public static string DetailYourReview {
            get {
                return ResourceManager.GetString("DetailYourReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có địa điểm yêu thích nào.
        /// </summary>
        public static string EmptyFavoritesText {
            get {
                return ResourceManager.GetString("EmptyFavoritesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khám Phá Vĩnh Khánh 🍜.
        /// </summary>
        public static string ExploreTitle {
            get {
                return ResourceManager.GetString("ExploreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu thích của tôi.
        /// </summary>
        public static string FavoritesTitle {
            get {
                return ResourceManager.GetString("FavoritesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cách bạn {0}km.
        /// </summary>
        public static string HomeDistanceKm {
            get {
                return ResourceManager.GetString("HomeDistanceKm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cách bạn {0}m.
        /// </summary>
        public static string HomeDistanceMeters {
            get {
                return ResourceManager.GetString("HomeDistanceMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin chào 👋.
        /// </summary>
        public static string HomeGreeting {
            get {
                return ResourceManager.GetString("HomeGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to đánh giá.
        /// </summary>
        public static string HomeReviews {
            get {
                return ResourceManager.GetString("HomeReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sắp xếp ↕.
        /// </summary>
        public static string HomeSort {
            get {
                return ResourceManager.GetString("HomeSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy món ăn hoặc quán nào.
        /// </summary>
        public static string NotFoundText {
            get {
                return ResourceManager.GetString("NotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm trong mục yêu thích....
        /// </summary>
        public static string SearchFavoritesPlaceholder {
            get {
                return ResourceManager.GetString("SearchFavoritesPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm quán ăn....
        /// </summary>
        public static string SearchMapPlaceholder {
            get {
                return ResourceManager.GetString("SearchMapPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm quán, món ăn (VD: lẩu bò, ốc)....
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiên bản 1.0.0.
        /// </summary>
        public static string SettingsAboutDesc {
            get {
                return ResourceManager.GetString("SettingsAboutDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Về ứng dụng.
        /// </summary>
        public static string SettingsAboutTitle {
            get {
                return ResourceManager.GetString("SettingsAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khám phá ẩm thực Vĩnh Khánh.
        /// </summary>
        public static string SettingsFooterTagline {
            get {
                return ResourceManager.GetString("SettingsFooterTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v1.0.0  ·  Made with ❤️ in Vietnam.
        /// </summary>
        public static string SettingsFooterVersion {
            get {
                return ResourceManager.GetString("SettingsFooterVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã chuyển sang.
        /// </summary>
        public static string SettingsLanguageChangedMsg {
            get {
                return ResourceManager.GetString("SettingsLanguageChangedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi ngôn ngữ thành công.
        /// </summary>
        public static string SettingsLanguageChangedTitle {
            get {
                return ResourceManager.GetString("SettingsLanguageChangedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn ngôn ngữ cho nội dung app.
        /// </summary>
        public static string SettingsLanguageDesc {
            get {
                return ResourceManager.GetString("SettingsLanguageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ hiển thị.
        /// </summary>
        public static string SettingsLanguageTitle {
            get {
                return ResourceManager.GetString("SettingsLanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhận thông báo về địa điểm mới.
        /// </summary>
        public static string SettingsPushDesc {
            get {
                return ResourceManager.GetString("SettingsPushDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo đẩy.
        /// </summary>
        public static string SettingsPushTitle {
            get {
                return ResourceManager.GetString("SettingsPushTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quét mã QR để xem chi tiết địa điểm.
        /// </summary>
        public static string SettingsQrDesc {
            get {
                return ResourceManager.GetString("SettingsQrDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mở →.
        /// </summary>
        public static string SettingsQrOpen {
            get {
                return ResourceManager.GetString("SettingsQrOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quét mã QR.
        /// </summary>
        public static string SettingsQrTitle {
            get {
                return ResourceManager.GetString("SettingsQrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chia sẻ trải nghiệm của bạn.
        /// </summary>
        public static string SettingsRateDesc {
            get {
                return ResourceManager.GetString("SettingsRateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đánh giá ứng dụng.
        /// </summary>
        public static string SettingsRateTitle {
            get {
                return ResourceManager.GetString("SettingsRateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin.
        /// </summary>
        public static string SettingsSectionInfo {
            get {
                return ResourceManager.GetString("SettingsSectionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ &amp; Vùng.
        /// </summary>
        public static string SettingsSectionLanguage {
            get {
                return ResourceManager.GetString("SettingsSectionLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        public static string SettingsSectionNotifications {
            get {
                return ResourceManager.GetString("SettingsSectionNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công cụ.
        /// </summary>
        public static string SettingsSectionTools {
            get {
                return ResourceManager.GetString("SettingsSectionTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phát âm thanh khi có thông báo mới.
        /// </summary>
        public static string SettingsSoundDesc {
            get {
                return ResourceManager.GetString("SettingsSoundDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Âm thanh thông báo.
        /// </summary>
        public static string SettingsSoundTitle {
            get {
                return ResourceManager.GetString("SettingsSoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuỳ chỉnh trải nghiệm của bạn.
        /// </summary>
        public static string SettingsSubtitle {
            get {
                return ResourceManager.GetString("SettingsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu thích.
        /// </summary>
        public static string TabFavorites {
            get {
                return ResourceManager.GetString("TabFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string TabHome {
            get {
                return ResourceManager.GetString("TabHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản đồ.
        /// </summary>
        public static string TabMap {
            get {
                return ResourceManager.GetString("TabMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt.
        /// </summary>
        public static string TabSettings {
            get {
                return ResourceManager.GetString("TabSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã lưu {0} vào yêu thích.
        /// </summary>
        public static string ToastAddedFavorite {
            get {
                return ResourceManager.GetString("ToastAddedFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xóa {0} khỏi yêu thích.
        /// </summary>
        public static string ToastRemovedFavorite {
            get {
                return ResourceManager.GetString("ToastRemovedFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔥 Top Quán Yêu Thích.
        /// </summary>
        public static string TopFavorites {
            get {
                return ResourceManager.GetString("TopFavorites", resourceCulture);
            }
        }
    }
}
