name: vinh_khanh_tourism
description: Ứng dụng thuyết minh đa ngôn ngữ cho phố ẩm thực Vĩnh Khánh
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # HTTP & API
  http: ^1.1.0

  # Location & Map
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0

  # Audio Player
  audioplayers: ^5.2.1

  # QR Code Scanner
  mobile_scanner: ^3.5.5

  # Local Storage
  shared_preferences: ^2.2.2

  # Internationalization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # UI Components
  cupertino_icons: ^1.0.6

  flutter_tts: ^3.8.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/
  #   - assets/icons/

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700
