using Server.Models;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Server.Models
{
    public static class GoogleLanguages
    {
        // 1. Danh sách ngôn ngữ (A-Z theo key)
        public static readonly Dictionary<string, string> SupportedLanguages = new()
        {
            { "af", "Tiếng Afrikaans" },
            { "am", "Tiếng Amharic" },
            { "ar", "Tiếng Ả Rập" },
            { "az", "Tiếng Azerbaijan" },
            { "bg", "Tiếng Bulgaria" },
            { "bn", "Tiếng Bengal" },
            { "bs", "Tiếng Bosnia" },
            { "ca", "Tiếng Catalan" },
            { "ceb", "Tiếng Cebuano" },
            { "co", "Tiếng Corsica" },
            { "cs", "Tiếng Séc" },
            { "cy", "Tiếng Wales" },
            { "da", "Tiếng Đan Mạch" },
            { "de", "Tiếng Đức" },
            { "el", "Tiếng Hy Lạp" },
            { "en", "Tiếng Anh" },
            { "eo", "Tiếng Esperanto" },
            { "es", "Tiếng Tây Ban Nha" },
            { "et", "Tiếng Estonia" },
            { "eu", "Tiếng Basque" },
            { "fa", "Tiếng Ba Tư" },
            { "fi", "Tiếng Phần Lan" },
            { "fil", "Tiếng Philippines" },
            { "fr", "Tiếng Pháp" },
            { "fy", "Tiếng Frisian" },
            { "ga", "Tiếng Ireland" },
            { "gd", "Tiếng Gaelic (Scotland)" },
            { "gl", "Tiếng Galicia" },
            { "gu", "Tiếng Gujarati" },
            { "ha", "Tiếng Hausa" },
            { "haw", "Tiếng Hawaii" },
            { "he", "Tiếng Do Thái" },
            { "hi", "Tiếng Hindi" },
            { "hr", "Tiếng Croatia" },
            { "hu", "Tiếng Hungary" },
            { "hy", "Tiếng Armenia" },
            { "id", "Tiếng Indonesia" },
            { "ig", "Tiếng Igbo" },
            { "is", "Tiếng Iceland" },
            { "it", "Tiếng Ý" },
            { "ja", "Tiếng Nhật" },
            { "jv", "Tiếng Java" },
            { "ka", "Tiếng Gruzia" },
            { "kk", "Tiếng Kazakh" },
            { "km", "Tiếng Khmer" },
            { "kn", "Tiếng Kannada" },
            { "ko", "Tiếng Hàn" },
            { "ku", "Tiếng Kurdish" },
            { "ky", "Tiếng Kyrgyz" },
            { "la", "Tiếng Latin" },
            { "lb", "Tiếng Luxembourg" },
            { "lo", "Tiếng Lào" },
            { "lt", "Tiếng Litva" },
            { "lv", "Tiếng Latvia" },
            { "mg", "Tiếng Malagasy" },
            { "mi", "Tiếng Maori" },
            { "mk", "Tiếng Macedonia" },
            { "ml", "Tiếng Malayalam" },
            { "mn", "Tiếng Mông Cổ" },
            { "mr", "Tiếng Marathi" },
            { "ms", "Tiếng Mã Lai" },
            { "mt", "Tiếng Malta" },
            { "my", "Tiếng Myanmar" },
            { "ne", "Tiếng Nepal" },
            { "nl", "Tiếng Hà Lan" },
            { "no", "Tiếng Na Uy" },
            { "or", "Tiếng Odia" },
            { "pa", "Tiếng Punjab" },
            { "pl", "Tiếng Ba Lan" },
            { "ps", "Tiếng Pashto" },
            { "pt", "Tiếng Bồ Đào Nha" },
            { "ro", "Tiếng Romania" },
            { "ru", "Tiếng Nga" },
            { "si", "Tiếng Sinhala" },
            { "sk", "Tiếng Slovakia" },
            { "sl", "Tiếng Slovenia" },
            { "sm", "Tiếng Samoa" },
            { "sn", "Tiếng Shona" },
            { "so", "Tiếng Somali" },
            { "sq", "Tiếng Albania" },
            { "sr", "Tiếng Serbia" },
            { "st", "Tiếng Sesotho" },
            { "su", "Tiếng Sunda" },
            { "sv", "Tiếng Thụy Điển" },
            { "sw", "Tiếng Swahili" },
            { "ta", "Tiếng Tamil" },
            { "te", "Tiếng Telugu" },
            { "tg", "Tiếng Tajik" },
            { "th", "Tiếng Thái" },
            { "tk", "Tiếng Turkmen" },
            { "tr", "Tiếng Thổ Nhĩ Kỳ" },
            { "tt", "Tiếng Tatar" },
            { "ug", "Tiếng Uyghur" },
            { "uk", "Tiếng Ukraina" },
            { "ur", "Tiếng Urdu" },
            { "uz", "Tiếng Uzbek" },
            { "vi", "Tiếng Việt" },
            { "xh", "Tiếng Xhosa" },
            { "yo", "Tiếng Yoruba" },
            { "yue", "Tiếng Quảng Đông" },
            { "zh-cn", "Tiếng Trung (Giản thể)" },
            { "zh-tw", "Tiếng Trung (Phồn thể)" },
            { "zu", "Tiếng Zulu" }
        };

        // 2. Mapping giọng đọc (A-Z theo key)
        public static readonly Dictionary<string, string> VoiceMappings = new()
        {
            { "af", "af-ZA-Standard-A" },
            { "am", "am-ET-Standard-A" },
            { "ar", "ar-XA-Standard-A" },
            { "az", "az-AZ-Standard-A" },
            { "bg", "bg-BG-Standard-A" },
            { "bn", "bn-IN-Standard-A" },
            { "bs", "bs-BA-Standard-A" },
            { "ca", "ca-ES-Standard-A" },
            { "ceb", "fil-PH-Standard-A" },
            { "co", "fr-FR-Standard-A" },
            { "cs", "cs-CZ-Standard-A" },
            { "cy", "cy-GB-Standard-A" },
            { "da", "da-DK-Standard-A" },
            { "de", "de-DE-Standard-A" },
            { "el", "el-GR-Standard-A" },
            { "en", "en-US-Standard-D" },
            { "eo", "es-ES-Standard-A" },
            { "es", "es-ES-Standard-A" },
            { "et", "et-EE-Standard-A" },
            { "eu", "eu-ES-Standard-A" },
            { "fa", "fa-IR-Standard-A" },
            { "fi", "fi-FI-Standard-A" },
            { "fil", "fil-PH-Standard-A" },
            { "fr", "fr-FR-Standard-A" },
            { "fy", "nl-NL-Standard-A" },
            { "ga", "en-IE-Standard-A" },
            { "gd", "en-GB-Standard-A" },
            { "gl", "gl-ES-Standard-A" },
            { "gu", "gu-IN-Standard-A" },
            { "ha", "ha-NG-Standard-A" },
            { "haw", "en-US-Standard-A" },
            { "he", "he-IL-Standard-A" },
            { "hi", "hi-IN-Standard-A" },
            { "hr", "hr-HR-Standard-A" },
            { "hu", "hu-HU-Standard-A" },
            { "hy", "hy-AM-Standard-A" },
            { "id", "id-ID-Standard-A" },
            { "ig", "en-NG-Standard-A" },
            { "is", "is-IS-Standard-A" },
            { "it", "it-IT-Standard-A" },
            { "ja", "ja-JP-Standard-A" },
            { "jv", "jv-ID-Standard-A" },
            { "ka", "ka-GE-Standard-A" },
            { "kk", "kk-KZ-Standard-A" },
            { "km", "km-KH-Standard-A" },
            { "kn", "kn-IN-Standard-A" },
            { "ko", "ko-KR-Standard-A" },
            { "ku", "tr-TR-Standard-A" },
            { "ky", "ru-RU-Standard-A" },
            { "la", "it-IT-Standard-A" },
            { "lb", "de-DE-Standard-A" },
            { "lo", "lo-LA-Standard-A" },
            { "lt", "lt-LT-Standard-A" },
            { "lv", "lv-LV-Standard-A" },
            { "mg", "fr-FR-Standard-A" },
            { "mi", "en-NZ-Standard-A" },
            { "mk", "mk-MK-Standard-A" },
            { "ml", "ml-IN-Standard-A" },
            { "mn", "mn-MN-Standard-A" },
            { "mr", "mr-IN-Standard-A" },
            { "ms", "ms-MY-Standard-A" },
            { "mt", "mt-MT-Standard-A" },
            { "my", "my-MM-Standard-A" },
            { "ne", "ne-NP-Standard-A" },
            { "nl", "nl-NL-Standard-A" },
            { "no", "nb-NO-Standard-A" },
            { "or", "or-IN-Standard-A" },
            { "pa", "pa-IN-Standard-A" },
            { "pl", "pl-PL-Standard-A" },
            { "ps", "ps-AF-Standard-A" },
            { "pt", "pt-PT-Standard-A" },
            { "ro", "ro-RO-Standard-A" },
            { "ru", "ru-RU-Standard-A" },
            { "si", "si-LK-Standard-A" },
            { "sk", "sk-SK-Standard-A" },
            { "sl", "sl-SI-Standard-A" },
            { "sm", "en-US-Standard-A" },
            { "sn", "en-ZA-Standard-A" },
            { "so", "so-SO-Standard-A" },
            { "sq", "sq-AL-Standard-A" },
            { "sr", "sr-RS-Standard-A" },
            { "st", "en-ZA-Standard-A" },
            { "su", "su-ID-Standard-A" },
            { "sv", "sv-SE-Standard-A" },
            { "sw", "sw-KE-Standard-A" },
            { "ta", "ta-IN-Standard-A" },
            { "te", "te-IN-Standard-A" },
            { "tg", "ru-RU-Standard-A" },
            { "th", "th-TH-Standard-A" },
            { "tk", "tr-TR-Standard-A" },
            { "tr", "tr-TR-Standard-A" },
            { "tt", "ru-RU-Standard-A" },
            { "ug", "zh-CN-Standard-A" },
            { "uk", "uk-UA-Standard-A" },
            { "ur", "ur-PK-Standard-A" },
            { "uz", "uz-UZ-Standard-A" },
            { "vi", "vi-VN-Standard-A" },
            { "xh", "xh-ZA-Standard-A" },
            { "yo", "yo-NG-Standard-A" },
            { "yue", "yue-HK-Standard-A" },
            { "zh-cn", "cmn-CN-Standard-A" },
            { "zh-tw", "cmn-TW-Standard-A" },
            { "zu", "zu-ZA-Standard-A" }
        };
    }
}